export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";

export const GET_TV_SHOWS_REQUEST = "GET_TV_SHOWS_REQUEST";
export const GET_TV_SHOWS_SUCCESS = "GET_TV_SHOWS_SUCCESS";
export const GET_TV_SHOWS_FAIL = "GET_TV_SHOWS_FAIL";

export const CLEAR_CAROUSELS = "CLEAR_CAROUSELS";

export const GET_DETAILS_REQUEST = "GET_DETAILS_REQUEST";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
export const GET_DETAILS_FAIL = "GET_DETAILS_FAIL";

export const CLEAR_DETAILS = "CLEAR_DETAILS";

export const ON_LOAD_MORE_ITEMS_SUCCESS = "ON_LOAD_MORE_ITEMS_SUCCESS";
export const ON_LOAD_MORE_ITEMS_FAIL = "ON_LOAD_MORE_ITEMS_FAIL";
